# Import the .env file
spring.config.import=optional:file:.env[.properties]

spring.application.name=executr
server.port=${SERVER_PORT:8080}
spring.application.version=${APP_VER:1.0}

spring.profiles.active=${ACTIVE_PROFILE:pro}

frontend.base.url=${FRONTEND_BASE_URL:http://localhost:5173}